### ISSUE TITLE
[Discussion] 统一使用Python3.7

### ISSUE THREAD

**Issue by rexwangcc** [wuhan2020/api-server#28]
Python2.7 2019年已正式被deprecated并失去官方支持，此外`pathlib`, `f-string`, type-annotations等标准库和特性以及`black`等linter仅在Py3.x中可用或只官方支持Py3.x。(此issue可在server被容器化， 方便跨平台开发后开始解决。)

**Comment by daca-ao** [comment]
可以在 bootstrap 里面修改？

**Comment by daca-ao** [comment]
可以在 bootstrap 里面修改？
