### ISSUE TITLE
The requested URL was not found on the server http://127.0.0.1:9000/wuhan2020/

### ISSUE THREAD

**Issue by bboychencan** [wuhan2020/api-server#31]
error message:

Not Found
The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

**Comment by iceflying** [comment]
"/wuhan2020/" is not a valid handler. Please check `utils.py`, there are some handles. e.g. "/wuhan2020/hospital_list"

**Comment by thinkinnight** [comment]
README.md中没有写清楚，访问http://127.0.0.1:9000/wuhan2020/就是404，就像@iceflying 说的，在utils.py中找对应的handler，请求对应的handler接口，可以返回json。

**Comment by rexwangcc** [comment]
Sorry for the confusion, there are some mess around both the routes and the readme. Let's fix this ASAP. Also, I'm working on a live Swagger UI page to document the endpoints, which hopefully can release us from the documentation inconsistency hell.

**Comment by rexwangcc** [comment]
A live Swagger Page is available at root now, it is not functional yet, but I think this issue could be closed for now.
