### ISSUE TITLE
[Bug] Run Docker image error:  "exec: \"bash\": executable file not found in $PATH"

### ISSUE THREAD

**Issue by Alie** [wuhan2020/api-server#59]
`docker run --name api-server --publish 5000:5000 api-server:default`

docker: Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"bash\": executable file not found in $PATH": unknown.

**Comment by rexwangcc** [comment]
Hi, thanks for reporting this bug. This was introduced in a previous PR that uses `alpine` image than the full docker image. This is fixed in #58

**Comment by Alie** [comment]
OK, closing since duplicated.
