### ISSUE TITLE
[Enhancement] Add a category field to collect column in the data structure of logistics.在物流的数据结构中，增加一个收集数据的种类字段。

### ISSUE THREAD

**Issue by JaneConan** [wuhan2020/api-server#63]
Maybe want to add a category(type) column is ok.

**Comment by imononoke** [comment]
需要这些数据信息：

物流名称、是否为直达通道、物流区域、联系方式、发布时间、发布链接、审核状态、核实、物流区域、预计运输时间、计价规则、收件方式、网点查询网址、是否接受个人捐赠、备注

**Comment by imononoke** [comment]
info | key | type | 是否必填
-- | -- | -- | --
物流名称 | name | String | Y
出发地 | starting | String | Y
目的地 | destination | String | Y
是否直达 | isDirect | Boolean | Y
物流区域 | area | String | Y
联系方式 | contract | String | Y
发布时间 | publishDate | Date | Y
发布链接 | publishUrl | String (Url) | Y
审核状态 | status | Enum | Y
是否核实 | hasVerified | Boolean | Y
预计运输时间 | arriveDate | String | Y
计价规则 | valuation | String | Y
收件方式 | contactMethod | String | Y
网点查询网址 | inquireUrl | String (Url) | Y
是否接受个人捐赠 | acceptPersonalDonation | Boolean | Y
备注 | remark | String | N

**Comment by JaneConan** [comment]
@LiuChangFreeman @JamesBonddu 您们方便时，看一下，如果有需要完善的，再请我们小伙伴一起完善

**Comment by rexwangcc** [comment]
我现在开始实现这个issue，希望没有为时过晚。@imononoke 请问这个issue的意思是要求新建一个data model （除现有的accommodations, donation, supplies, hospitals, .. 之外）专门给物流么。

**Comment by imononoke** [comment]
@rexwangcc 应该是更新原有的Logistics（物流）data model，原来没有专门的物流data model吗？
刚又更新了下数据信息，原来的“物流区域” 现在改成出发地 和 目的地了。

**Comment by rexwangcc** [comment]
@imononoke 多谢告知，主项目的数据是有logistics的，不过api-server并没有实现这个。。。我现在实现一下好了。BTW, 我在想可能您不会实际上想submit这个issue到data-sync repo吧？

**Comment by imononoke** [comment]
诶，data-sync repo不需要logistics数据吗？
